[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ogf_lottery = "6T3ZLEyUat5Xa1EKnvHs1ovyhsTpx3upjWTKJpeV5KPX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
